<#
.SYNOPSIS
  Create/refresh optimal_demo project-local qmd collections + context tree.

.DESCRIPTION
  Expands scripts/qmd/qmd.index.yml (__REPO_ROOT__) into <repo>/.qmd/index.yml,
  then runs `qmd update`. Index DB stays under .qmd/ (gitignored).

.EXAMPLE
  powershell -File scripts\qmd\setup_collections.ps1
  powershell -File scripts\qmd\setup_collections.ps1 -Embed
#>
param(
    [switch]$Embed,
    [switch]$SkipUpdate
)

$ErrorActionPreference = "Stop"

function Assert-Qmd {
    if (-not (Get-Command qmd -ErrorAction SilentlyContinue)) {
        throw "qmd not found on PATH. Install: npm install -g @tobilu/qmd"
    }
}

Assert-Qmd

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "../..")).Path
$TemplatePath = Join-Path $PSScriptRoot "qmd.index.yml"
$QmdDir = Join-Path $RepoRoot ".qmd"
$IndexYml = Join-Path $QmdDir "index.yml"

if (-not (Test-Path -LiteralPath $TemplatePath)) {
    throw "Missing template: $TemplatePath"
}

Push-Location $RepoRoot
try {
    if (-not (Test-Path -LiteralPath $QmdDir)) {
        Write-Host "Initializing project-local qmd index at $QmdDir"
        & qmd init
        if ($LASTEXITCODE -ne 0) { throw "qmd init failed" }
    }

    $repoRootPosix = ($RepoRoot -replace '\\', '/')
    $template = Get-Content -LiteralPath $TemplatePath -Raw -Encoding UTF8
    $body = $template.Replace('__REPO_ROOT__', $repoRootPosix)

    # Keep previously resolved model URIs when present.
    $modelsBlock = $null
    if (Test-Path -LiteralPath $IndexYml) {
        $existing = Get-Content -LiteralPath $IndexYml -Raw -Encoding UTF8
        if ($existing -match '(?ms)^models:\r?\n(?:[ \t].*\r?\n?)+') {
            $modelsBlock = $Matches[0].TrimEnd()
        }
    }

    if ($modelsBlock) {
        if ($body -match '(?ms)^models:\r?\n(?:[ \t].*\r?\n?)+') {
            $body = $body -replace '(?ms)^models:\r?\n(?:[ \t].*\r?\n?)+', ($modelsBlock + "`n")
        } else {
            $body = $body.TrimEnd() + "`n`n" + $modelsBlock + "`n"
        }
    }

    $header = @(
        "# Generated by scripts/qmd/setup_collections.ps1 - do not commit (.qmd/ is gitignored)."
        "# Template: scripts/qmd/qmd.index.yml"
        ""
    ) -join "`n"

    Set-Content -LiteralPath $IndexYml -Value ($header + $body.TrimStart()) -Encoding utf8
    Write-Host "Wrote $IndexYml"

    if (-not $SkipUpdate) {
        Write-Host "Running qmd update..."
        & qmd update
        if ($LASTEXITCODE -ne 0) { throw "qmd update failed" }
    }

    if ($Embed) {
        Write-Host "Running qmd embed (may download GGUF models on first run)..."
        & qmd embed
        if ($LASTEXITCODE -ne 0) { throw "qmd embed failed" }
    }

    & qmd status
    & qmd collection list
    Write-Host ""
    Write-Host 'Done. Try: qmd search "HMSD GHTD3" -c docs-algo --format files -n 5'
    if (-not $Embed) {
        Write-Host "Optional: powershell -File scripts\qmd\reindex.ps1 -Embed"
    }
}
finally {
    Pop-Location
}
